import sys
sys.stdout.reconfigure(encoding="utf-8")
from fpdf import FPDF
pdf = FPDF()
pdf.add_page()
pdf.set_font("Arial","B",16)
pdf.cell(0,10,"Reporte de Productos - Murder Drones Shop",ln=True,align="C")
pdf.ln(10)
pdf.set_font("Arial","B",12)
pdf.cell(10,10,"ID",1)
pdf.cell(60,10,"Nombre",1)
pdf.cell(40,10,"Precio",1)
pdf.ln()
productos = [{"id":2,"nombre":"ola","precio":100.0},{"id":3,"nombre":"consolador","precio":200.0},{"id":4,"nombre":"marihuan","precio":1333.0},{"id":5,"nombre":"manzanas","precio":0.0}]
pdf.set_font("Arial","",12)
for p in productos:
    pdf.cell(10,10,str(p["id"]),1)
    pdf.cell(60,10,p["nombre"],1)
    pdf.cell(40,10,f"${p["precio"]:.2f}",1)
    pdf.ln()
pdf.ln(10)
pdf.set_font("Arial","I",10)
pdf.cell(0,10,"Generado por Uzi Doorman - Murder Drones",ln=True,align="C")
pdf.output("Handlers/reporte_productos.pdf")
print("PDF generado exitosamente")
